---
title: "EDS 230 Assignment 2"
author: "Scout Leonard"
date: "4/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
packages=c("here",
           "readr",
           "tidyverse")

for (i in packages) {
  if (require(i,character.only=TRUE)==FALSE) {
    install.packages(i,repos='http://cran.us.r-project.org')
  }
  else {
    require(i,character.only=TRUE)
  }
}

source(here("assignments", "assignment_2", "R", "almond_yield_function.R"))
```

# Read in Data

```{r}
climate_data <- read.table(here("assignments", "assignment_2", "data", "clim.txt"))
options(scipen = 999)
```

# Subset the Climat Data

```{r}
#filter climate dataset for february minimum temperature
feb_min_temps <- climate_data %>%
  filter(month == 2) %>% 
  group_by(wy) %>% 
  summarise(feb_min_temp_c = mean(tmin_c))

#filter climate dataset for february precipitation 
jan_precip <- climate_data %>% 
  filter(month == 1) %>%
  group_by(wy) %>% 
  summarise(total_jan_precip_mm = sum(precip))
```

# Summarize Results

```{r}
years_list <- jan_precip$wy
anomaly <- c()

for (i in 1:length(years_list)){
  
  anomaly[i] <- almond_yield(precip = jan_precip$total_jan_precip_mm[i],
                             temp = feb_min_temps$feb_min_temp_c[i])
  
}

anomaly
```

```{r Figure 1}
anomaly_df <- as.data.frame(cbind(years_list, 
                                  anomaly,
                                  jan_precip$total_jan_precip_mm,
                                  feb_min_temps$feb_min_temp_c))

colnames(anomaly_df) <- c("years", "anomaly", "ppt", "temp")

anomaly_df %>% 
  ggplot(aes(x = years)) +
  geom_line(aes(y = anomaly, color = "Almond Yield Anomaly (tons/acre)"),
            lwd = 1) +
  geom_line(aes(y = ppt, color = "Total January Precipitation (mm)"),
            lwd = 1) +
  xlab("Years") +
  ylab("Anomaly (tons/acre)") +
  scale_color_manual(values = c("red", "lightskyblue3")) +
  scale_y_continuous(sec.axis = sec_axis(trans = ~.*1,
                                         name = "Precipitation (mm)")) +
  ggtitle("Almond Yield Anomaly (1989-2010)") +
  labs(color = "Variable") +
  theme_light() +
  theme(axis.text.y.right = element_text(color = "lightskyblue3"),
        axis.title.y.right = element_text(color = "lightskyblue3"))
```